on:
  rss:
    url: 
      # 少数派
      - https://rsshub.app/sspai/index
      # kill-the-newsletter 邮件订阅
      - https://kill-the-newsletter.com/feeds/6hiq8ql6fhnjvy6f.xml
      # 月光博客
      # - https://www.williamlong.info/rss.xml
      # 小众软件
      - http://feed.appinn.com/
jobs:
  request:
    name: PUT INFO to CUBOX
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://cubox.pro/c/api/save/${{ secrets.API_KEY }}
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}",
              "folder":"RSS"
            }
      
