on:
  rss:
    url: https://hnrss.org/newest?points=300&count=4
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: http://122.51.131.110:8098/${{ secrets.BARK_TOKEN }}
          method: POST
          body: |
            {
              "body":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}"
            }
      
