on:
  rss:
    url: 
      - https://rsshub.app/sspai/index
      - https://kill-the-newsletter.com/feeds/6hiq8ql6fhnjvy6f.xml
jobs:
  request:
    name: PUT INFO to CUBOX
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://cubox.pro/c/api/save/${{ secrets.API_KEY }}
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}",
              "folder":"RSS"
            }
      # - name: Make a HTTP Request
      #   uses: actionsflow/axios@v1
      #   with:
      #     url: http://122.51.131.110:8098/${{ secrets.BARK_TOKEN }}
      #     method: POST
      #     body: |
      #       {
      #         "body":"${{ on.rss.outputs.link }}", 
      #         "title": "${{ on.rss.outputs.title }}"
      #       }
      
